import { env } from 'cloudflare:workers';
import { z } from 'zod';
import { seed } from '@/lib/gym';
import { getChatGPTUser } from '@/app/chatgpt-auth';
const schemas = {
 students:z.object({id:z.string().min(1),name:z.string().trim().min(2).max(100),email:z.string().email(),unit:z.enum(['Pryme Academia','Move Academia']),plan:z.string().min(1),status:z.enum(['Ativo','Pendente','Inativo']),expires:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)}),
 plans:z.object({id:z.string().min(1),name:z.string().trim().min(2).max(60),price:z.number().min(0).max(100000),features:z.string().max(1000),unit:z.enum(['Todas','Pryme Academia','Move Academia'])}),
 workouts:z.object({id:z.string().min(1),name:z.string().trim().min(2).max(100),student:z.string().min(1),unit:z.enum(['Pryme Academia','Move Academia']),goal:z.string().min(1),status:z.enum(['Rascunho','Publicado']),days:z.string().min(1).max(200),updated:z.string(),exercises:z.array(z.object({name:z.string().trim().min(2).max(100),sets:z.number().int().min(1).max(20),reps:z.string().min(1).max(40),rest:z.number().int().min(0).max(600)})).min(1).max(40)})
};
function db(){if(!env.DB)throw new Error('Database unavailable');return env.DB;}
async function initial(){const d=db();const marker=await d.prepare('SELECT id FROM records WHERE id = ?').bind('__initialized').first();if(!marker){const all=Object.entries(seed).flatMap(([kind,rows])=>rows.map(row=>d.prepare('INSERT OR IGNORE INTO records (id,kind,payload) VALUES (?,?,?)').bind(row.id,kind,JSON.stringify(row))));all.push(d.prepare('INSERT OR IGNORE INTO records (id,kind,payload) VALUES (?,?,?)').bind('__initialized','meta','{}'));await d.batch(all);}}
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:'Entre na sua conta para continuar.'},{status:401});try{await initial();const rows=await db().prepare('SELECT kind,payload FROM records WHERE kind != ?').bind('meta').all<{kind:string;payload:string}>();const data:Record<string,unknown[]>={students:[],plans:[],workouts:[]};const studentUnits=new Map(rows.results.filter(r=>r.kind==='students').map(r=>{const s=JSON.parse(r.payload);return [s.id,s.unit]}));for(const row of rows.results){const record=JSON.parse(row.payload);if(row.kind==='workouts')record.unit=studentUnits.get(record.student)||record.unit;if(user.role==='unit_admin'&&record.unit!==user.unit&&!(row.kind==='plans'&&record.unit==='Todas'))continue;data[row.kind]?.push(record)}return Response.json(data);}catch(e){console.error(e);return Response.json({error:'Não foi possível carregar os dados. Tente novamente.'},{status:503});}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Entre na sua conta para continuar.'},{status:401});if(request.headers.get('origin') && request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Origem inválida.'},{status:403});try{const body=await request.json() as {kind:string;record:unknown};const kind=body.kind as keyof typeof schemas;if(!schemas[kind])return Response.json({error:'Registro inválido.'},{status:400});const parsed=schemas[kind].safeParse(body.record);if(!parsed.success)return Response.json({error:'Confira os campos obrigatórios e os valores informados.'},{status:400});const record=parsed.data;const d=db();if(user.role==='unit_admin'){
 if(!user.unit||record.unit!==user.unit)return Response.json({error:'Você só pode gerenciar registros da sua academia.'},{status:403});
 const existing=await d.prepare('SELECT kind,payload FROM records WHERE id=?').bind(record.id).first<{kind:string;payload:string}>();
 let existingUnit=existing?JSON.parse(existing.payload).unit:null;if(existing?.kind==='workouts'){const owner=await d.prepare('SELECT payload FROM records WHERE id=? AND kind=?').bind(JSON.parse(existing.payload).student,'students').first<{payload:string}>();existingUnit=owner?JSON.parse(owner.payload).unit:null;}if(existing&&(existing.kind!==kind||existingUnit!==user.unit))return Response.json({error:'Você não tem acesso a este registro.'},{status:403});
 }if(kind==='students'){const s=record as z.infer<typeof schemas.students>;const plan=await d.prepare('SELECT payload FROM records WHERE id=? AND kind=?').bind(s.plan,'plans').first<{payload:string}>();if(!plan)return Response.json({error:'Selecione um plano válido.'},{status:400});const p=JSON.parse(plan.payload);if(p.unit!=='Todas'&&p.unit!==s.unit)return Response.json({error:'O plano não está disponível nesta unidade.'},{status:400});}if(kind==='workouts'){const w=record as z.infer<typeof schemas.workouts>;const student=await d.prepare('SELECT payload FROM records WHERE id=? AND kind=?').bind(w.student,'students').first<{payload:string}>();if(!student)return Response.json({error:'Selecione um aluno válido.'},{status:400});const studentUnit=JSON.parse(student.payload).unit;if(user.role==='unit_admin'&&studentUnit!==user.unit)return Response.json({error:'Este aluno pertence a outra academia.'},{status:403});w.unit=studentUnit;w.updated=new Date().toISOString().slice(0,10);}await d.prepare('INSERT INTO records (id,kind,payload) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload WHERE records.kind=excluded.kind').bind(record.id,kind,JSON.stringify(record)).run();return Response.json({record});}catch(e){console.error(e);return Response.json({error:'Não foi possível salvar. Seus dados continuam no formulário.'},{status:503});}}

