export type Student = {id:string;name:string;email:string;unit:string;plan:string;status:string;expires:string};
export type Plan = {id:string;name:string;price:number;features:string;unit:string};
export type Exercise = {name:string;sets:number;reps:string;rest:number};
export type Workout = {id:string;name:string;student:string;unit:string;goal:string;status:string;days:string;exercises:Exercise[];updated:string};
export type GymData = {students:Student[];plans:Plan[];workouts:Workout[]};
export const units = ['Pryme Academia','Move Academia'];
export const seed:GymData = {
 plans:[{id:'p1',name:'Essencial',price:89,features:'Musculação livre\nAvaliação física\nAcesso à unidade',unit:'Todas'},{id:'p2',name:'Total',price:149,features:'Musculação livre\nTodas as aulas coletivas\nAvaliação física\nAcesso às duas unidades',unit:'Todas'},{id:'p3',name:'Anual Black',price:119,features:'Compromisso de 12 meses\nTodas as aulas coletivas\nAcesso às duas unidades',unit:'Todas'}],
 students:[['s1','Marina Santos','marina@example.com',units[0],'p2','Ativo','2026-10-28'],['s2','Lucas Oliveira','lucas@example.com',units[0],'p1','Ativo','2026-10-05'],['s3','Ana Beatriz Costa','ana@example.com',units[1],'p2','Ativo','2026-10-06'],['s4','Pedro Almeida','pedro@example.com',units[0],'p3','Ativo','2026-11-12'],['s5','Juliana Ribeiro','juliana@example.com',units[1],'p1','Pendente','2026-10-03'],['s6','Rafael Martins','rafael@example.com',units[1],'p2','Ativo','2026-10-22'],['s7','Camila Ferreira','camila@example.com',units[0],'p2','Ativo','2026-10-08'],['s8','Bruno Lima','bruno@example.com',units[1],'p1','Inativo','2026-09-28']].map(([id,name,email,unit,plan,status,expires])=>({id,name,email,unit,plan,status,expires})),
 workouts:[{id:'w1',name:'Pernas · Hipertrofia',student:'s1',unit:units[0],goal:'Hipertrofia',status:'Publicado',days:'Segunda, quarta e sexta',updated:'2026-10-02',exercises:[{name:'Agachamento livre',sets:4,reps:'10–12',rest:90},{name:'Leg press 45°',sets:3,reps:'12–15',rest:60},{name:'Cadeira extensora',sets:3,reps:'12',rest:60},{name:'Stiff com barra',sets:3,reps:'10–12',rest:60}]},{id:'w2',name:'Superiores · Força',student:'s2',unit:units[0],goal:'Força',status:'Rascunho',days:'Terça e quinta',updated:'2026-10-02',exercises:[{name:'Supino reto',sets:4,reps:'8–10',rest:90},{name:'Remada curvada',sets:3,reps:'10–12',rest:60}]},{id:'w3',name:'Corpo todo · Adaptação',student:'s3',unit:units[1],goal:'Condicionamento',status:'Publicado',days:'Segunda, quarta e sexta',updated:'2026-10-01',exercises:[{name:'Agachamento no smith',sets:3,reps:'12',rest:60},{name:'Puxada frontal',sets:3,reps:'12',rest:60}]}]
};
